import { StyleSheet } from 'react-native';
import { colors, spacing, radius, typography } from '@/theme/tokens';

export const GLASS_CARD = {
  backgroundColor: 'rgba(255,255,255,0.4)',
  borderColor: 'rgba(255,255,255,0.6)',
  borderWidth: 1,
} as const;

export const wizardStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },

  wizardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.marginMobile,
    paddingTop: spacing.base,
    paddingBottom: spacing.sm,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepIndicator: { ...typography.labelSm, color: colors.outline, letterSpacing: 2 },
  stepTitle: { ...typography.headlineMd, color: colors.onBackground, marginTop: 2 },

  progressTrack: {
    height: 4,
    backgroundColor: colors.surfaceVariant,
    marginHorizontal: spacing.marginMobile,
    borderRadius: 2,
    marginBottom: spacing.md,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.tertiaryFixedDim,
    borderRadius: 2,
  },

  stepContent: {
    paddingHorizontal: spacing.marginMobile,
    paddingBottom: spacing.xl,
  },

  fieldLabel: { ...typography.labelLg, color: colors.onBackground, marginBottom: spacing.sm },
  textArea: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radius.default,
    padding: spacing.md,
    ...typography.bodyMd,
    color: colors.onBackground,
    minHeight: 100,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  charCount: { ...typography.labelSm, color: colors.outline, textAlign: 'right', marginTop: 4 },

  typeList: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  typeChip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  typeChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  typeChipText: { ...typography.labelLg, color: colors.onSurfaceVariant },
  typeChipTextActive: { color: colors.onPrimary },
  emptyTypes: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radius.default,
  },
  emptyTypesText: { ...typography.bodyMd, color: colors.outline, flex: 1 },

  mapWrapper: { alignItems: 'center', paddingVertical: spacing.md },
  mapCircle: {
    width: 288,
    height: 288,
    borderRadius: 144,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderColor: 'rgba(255,255,255,0.6)',
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(45,58,45,0.15)',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 1,
    shadowRadius: 40,
    elevation: 6,
  },
  mapPinWrapper: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ripple: {
    position: 'absolute',
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(183,245,105,0.35)',
  },
  mapPin: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },

  infoCard: {
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderColor: 'rgba(255,255,255,0.6)',
    borderWidth: 1,
    borderRadius: 16,
    marginHorizontal: spacing.marginMobile,
    padding: spacing.md,
    gap: spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 32,
    elevation: 2,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.gutter,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(68,71,72,0.1)',
  },
  infoRowBorderless: { paddingBottom: 0, borderBottomWidth: 0 },
  infoIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.5,
  },
  infoLabel: { ...typography.labelSm, color: colors.outline },
  infoValue: { ...typography.bodyLg, color: colors.onBackground },
  infoValueMuted: { ...typography.bodyMd, color: colors.outline },
  manualLocationCard: {
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderColor: 'rgba(255,255,255,0.6)',
    borderWidth: 1,
    marginHorizontal: spacing.marginMobile,
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.default,
    gap: spacing.sm,
  },
  manualLocationText: { ...typography.bodyMd, color: colors.onSurfaceVariant },
  manualLocationRow: { flexDirection: 'row', gap: spacing.sm },
  coordInput: {
    flex: 1,
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radius.default,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    ...typography.bodyMd,
    color: colors.onBackground,
  },

  cameraBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.marginMobile,
    paddingBottom: spacing.lg,
    paddingTop: spacing.md,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  cameraCancel: { padding: 12 },
  shutterButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#fff',
  },

  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  photoThumb: {
    width: 96,
    height: 96,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: colors.surfaceContainerHigh,
  },
  photoRemove: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPhotoBtn: {
    width: 96,
    height: 96,
    borderRadius: 12,
    backgroundColor: colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  permissionView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    padding: spacing.marginMobile,
  },
  permissionText: { ...typography.bodyMd, color: colors.onSurfaceVariant, textAlign: 'center' },

  reviewLabel: { ...typography.labelLg, color: colors.outline, letterSpacing: 1 },
  reviewValue: { ...typography.bodyLg, color: colors.onBackground, marginTop: 2 },
  reviewSub: { ...typography.labelSm, color: colors.outline, marginTop: 2 },
  reviewPhotoRow: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm },
  reviewPhoto: {
    width: 72,
    height: 72,
    borderRadius: 8,
    backgroundColor: colors.surfaceContainerHigh,
  },
  reviewNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    marginTop: spacing.lg,
    padding: spacing.md,
    backgroundColor: colors.secondaryContainer,
    borderRadius: radius.default,
    opacity: 0.8,
  },
  reviewNoticeText: { ...typography.labelSm, color: colors.onSecondaryContainer, flex: 1 },

  footer: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.marginMobile,
    paddingVertical: spacing.md,
    paddingBottom: spacing.lg,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: 16,
    borderRadius: 9999,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  primaryButtonDisabled: { opacity: 0.4 },
  primaryButtonText: { ...typography.labelLg, color: colors.onPrimary },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: 16,
    paddingHorizontal: spacing.md,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: colors.secondary,
  },
  secondaryButtonText: { ...typography.labelLg, color: colors.secondary },
});
